spring.application.name=back
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true
server.port=8081

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.driverClassName=oracle.jdbc.driver.OracleDriver
spring.datasource.username=scott
spring.datasource.password=1004

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.generate_statistics=false

kakao.secret-key=DEVE3E87C0496C26F10BA5251AC88B93B8BFF524

##jwt SECRET_KEY
jwt.secret-key=zCZSwys5xNyWlfwR7nP51kYvfviH6kIN

##Gmail STMP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=naong0711@gmail.com
spring.mail.password=xexv irip eiue jzrm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

##이메일 인증
app.email.verify-url-base=http://localhost:8080/email/verify?token=

# Kakao OAuth2 설정
spring.security.oauth2.client.registration.kakao.client-id=69defb2d16d643055c6d13227979a378
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/api/user/login/kakao/code
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.client-name=Kakao
spring.security.oauth2.client.registration.kakao.scope=profile_nickname

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

#Gemini API
gemini.api-key=
gemini.api-url=

#kakao api key
kakao.api.key = 
